apiVersion: v2
name: wordpress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: wordpress
    version: "12.2.5"
    repository: "https://charts.bitnami.com/bitnami"
