---
wordpress:
  service:
    type: ClusterIP
  
  ingress:
    enabled: true
    pathType: Prefix
    hostname: blog.172-17-0-9.nip.io
    tls: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
